version: '3.4'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    ports:
      - '5051:5051'
    volumes:
      - .:/home/node/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - notused:/app/node_modules
    env_file:
      - .env
volumes:
  notused:
